# GitHub Actions CI/CD pipeline for PyMetallic

name: CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [ 3.10, 3.11, 3.12, 3.13 ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pytest black mypy wheel

      - name: Check Swift availability
        run: swift --version

      - name: Build Swift bridge
        run: make build

      - name: Install package
        run: pip install -e .

      - name: Run tests
        run: python test_pymetal.py

      - name: Run type checking
        run: make typecheck

      - name: Check code formatting
        run: |
          black --check pymetallic/*.py examples/*.py tests/*.py

  build:
    needs: test
    runs-on: macos-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build distribution
        run: make dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/

