name: macOS CI

on: [ push, pull_request ]

jobs:
  test:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: python -m pip install -e .
      - run: python -m pip install pytest numpy
      - run: pytest -q
