name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: uv sync --dev
      - run: uv run ruff check .
      - run: uv run black --check .
      - run: uv run mypy src/pymetallic --ignore-missing-imports

  test:
    runs-on: macos-13
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: uv sync --dev
      - run: make build
      - run: make test
      - run: make examples
